
export const heroGrid = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737782705/apple/home/asmlexcmxw8jcg00fzuc.png",
    title: "iPhone 14 Pro",
    titleCSS: "text-[30px] text-[#F5F5F7] font-bold lg:text-[40px]",
    text: "Pro. Beyond.",
    textCSS: "text-[16px] text-[#F5F5F7] font-normal lg:text-[21px]",
    linkOne: "Learn more",
    destiOne: "/iphone",
    linkTwo: "Buy",
    destiTwo: "/store",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737782705/apple/home/wqqbwjoxlhakuz7nnc53.png",
    title: "iPad",
    titleCSS: "text-[#1D1D1F] font-bold lg:text-[40px] text-[30px]",
    text: "Lovable. Drawable. Magical.",
    textCSS: "text-[16px] text-[#1D1D1F] font-normal lg:text-[21px]",
    linkOne: "Learn more",
    linkTwo: "Buy",
    destiOne: "/iphone",
    destiTwo: "/store",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737782707/apple/home/qdp04ihvdglgwkf1eitl.png",
    icon: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737820274/apple/home/cxfpaahe5kebzdjymr75.svg",
    title: "AirPods",
    titleCSS: "text-[#1D1D1F] font-bold lg:text-[40px] text-[30px]",
    text: "Share the joy.",
    textCSS: "text-[16px] text-[#1D1D1F] font-normal lg:text-[21px]",
    linkOne: "Shop",
    destiOne: "/store",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737782706/apple/home/agcpukrpn0dreberl9es.png",
    icon: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737820275/apple/home/vsu8fzpm7dibgoerpn85.svg",
    text: "A healthy leap ahead.",
    textCSS: "text-[16px] text-[#F5F5F7] font-normal lg:text-[21px]",
    linkOne: "Learn more",
    linkTwo: "Buy",
    destiOne: "/iphone",
    destiTwo: "/store",
  },
];

export const heroGridTwo = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737922742/apple/home/y8dwicn9zzy24trorozo.png",
    icon: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737922766/apple/home/bycrvivllhwwspc6pw5h.svg",
    text: "Adventure awaits.",
    textCSS: "text-[16px] lg:text-[21px] tracking-[0.34px] text-[#1D1D1F]",
    linkOne: "Learn more",
    destiOne: "/accessories",
    linkTwo: "Buy",
    destiTwo: "/store",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737922742/apple/home/yumrlms6lgsmk4xpkclb.png",
    icon: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737922766/apple/home/xnvsyaut8igb98s6hlfc.svg",
    text: "Get up to 3% Daily Cash back with every purchase.",
    textCSS: "text-[16px] lg:text-[21px] tracking-[0.34px] text-[#1D1D1F]",
    linkOne: "Learn more",
    destiOne: "/accessories",
    linkTwo: "Apply now",
    destiTwo: "/store",
  },
];

export const carousel = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737931098/apple/home/carousel/mv9micsjlqy8bbjfmybu.jpg",
    text: "Drama · Family. It's a killer.",
    textCSS: "text-[12px] lg:text-[20px] text-white",
    button: "Stream now",
    desti: "/tv",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737777809/apple/home/g4cnp4ashxtqw3mlbd9f.png",
    text: "Comedy · Start your holidays on a high note.",
    textCSS: "text-[12px] lg:text-[20px] text-white",
    button: "Stream now",
    desti: "/tv",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737926026/apple/home/carousel/spvcmoiwqjrbji5f92cn.jpg",
    text: "Thriller · Suspense. Some advice saves lives; hers might end yours.",
    textCSS: "text-[12px] lg:text-[20px] text-white",
    button: "Stream now",
    desti: "/tv",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737926026/apple/home/carousel/n8swtb9ieoqxor3u1itx.jpg",
    text: "Thriller · Superhero. She sees the future, but can she stop the past from catching up?",
    textCSS: "text-[12px] lg:text-[20px] text-white",
    button: "Stream now",
    desti: "/tv",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dmrr92p4s/image/upload/v1737926026/apple/home/carousel/wbrjbljldeit2zo18wvw.jpg",
    text: "Action · Sci-Fi. He's got the power, but does he have what it takes to save the world?",
    textCSS: "text-[12px] lg:text-[20px] text-white",
    button: "Stream now",
    desti: "/tv",
  },
];